"""WAF (Web Application Firewall) detection tool for red team reconnaissance.

Identifies deployed WAF products by passively fingerprinting:
  - Response headers (vendor-specific header names and values)
  - Set-Cookie header names (vendor-specific session cookie names)
  - Response body markers (vendor-specific error page strings)
  - Probe responses (send a simple SQL-injection payload and analyse
    the error/block response for WAF signatures)

Severity / impact classifications:
  DETECTED     — High confidence: 2+ independent signals match
  PROBABLE     — Medium confidence: 1 signal matches
  NOT_DETECTED — No known WAF fingerprints found

Stdlib-only: http.client + urllib.  No external dependencies.
"""

from __future__ import annotations

import http.client
import ssl
import urllib.parse
from typing import NamedTuple

from cai.sdk.agents import function_tool
from cai.tool_registry import TOOL_REGISTRY

# ---------------------------------------------------------------------------
# Fingerprint database
# Each entry: (waf_name, [header_fingerprints], [cookie_fingerprints], [body_fingerprints])
# header_fingerprints: list of (header_name_lower, value_substring_lower | None)
#   value_substring_lower=None means "header present with any value"
# cookie_fingerprints: list of cookie name substrings (lower-case)
# body_fingerprints: list of body substrings (lower-case, checked in block responses)
# ---------------------------------------------------------------------------

class _WAFEntry(NamedTuple):
    name: str
    headers: list[tuple[str, str | None]]  # (header_lower, value_lower_or_None)
    cookies: list[str]
    body_markers: list[str]


_WAF_DB: list[_WAFEntry] = [
    _WAFEntry(
        name="Cloudflare",
        headers=[
            ("cf-ray", None),
            ("cf-cache-status", None),
            ("server", "cloudflare"),
        ],
        cookies=["__cfduid", "__cfuid", "cf_clearance"],
        body_markers=[
            "cloudflare ray id",
            "attention required! | cloudflare",
            "error 1020",
            "1020 access denied",
        ],
    ),
    _WAFEntry(
        name="AWS WAF / CloudFront",
        headers=[
            ("x-amz-cf-id", None),
            ("x-amz-cf-pop", None),
            ("x-amzn-requestid", None),
            ("server", "amazons3"),
            ("x-amzn-waf-action", None),
        ],
        cookies=["awsalb", "awsalbcors"],
        body_markers=[
            "request blocked",
            "aws waf",
        ],
    ),
    _WAFEntry(
        name="Akamai",
        headers=[
            ("x-check-cacheable", None),
            ("x-akamai-transformed", None),
            ("akamai-grn", None),
        ],
        cookies=["akamai_netsession", "akacd_"],
        body_markers=[
            "access denied | akamai",
            "reference #",
        ],
    ),
    _WAFEntry(
        name="Sucuri",
        headers=[
            ("x-sucuri-id", None),
            ("x-sucuri-cache", None),
        ],
        cookies=["sucuri_cloudproxy_uuid"],
        body_markers=[
            "sucuri website firewall",
            "access denied - sucuri website firewall",
        ],
    ),
    _WAFEntry(
        name="Imperva / Incapsula",
        headers=[
            ("x-iinfo", None),
            ("x-cdn", "incapsula"),
            ("incap_ses", None),
            ("visid_incap_", None),
        ],
        cookies=["incap_ses_", "visid_incap_"],
        body_markers=[
            "incapsula incident id",
            "powered by incapsula",
            "request unsuccessful. incapsula",
        ],
    ),
    _WAFEntry(
        name="F5 BIG-IP ASM",
        headers=[
            ("x-waf-event-info", None),
            ("bigipserver", None),
        ],
        cookies=["ts", "bigip"],
        body_markers=[
            "the requested url was rejected",
            "please consult with your administrator",
            "f5",
        ],
    ),
    _WAFEntry(
        name="Barracuda WAF",
        headers=[
            ("x-barracuda-connect", None),
            ("barra_counter_session", None),
        ],
        cookies=["barra_counter_session"],
        body_markers=[
            "barracuda networks",
            "you have been blocked",
        ],
    ),
    _WAFEntry(
        name="ModSecurity",
        headers=[
            ("server", "mod_security"),
            ("server", "modsecurity"),
        ],
        cookies=[],
        body_markers=[
            "not acceptable!",
            "406 not acceptable",
            "this error was generated by mod_security",
        ],
    ),
    _WAFEntry(
        name="Fortiweb",
        headers=[
            ("x-first-seen", None),
            ("fortigate", None),
        ],
        cookies=["cookiesession1"],
        body_markers=[
            "fortiweb",
            "the url you requested has been blocked",
        ],
    ),
    _WAFEntry(
        name="Wordfence",
        headers=[],
        cookies=["wordfence_verifiedHuman"],
        body_markers=[
            "generated by wordfence",
            "your access to this site has been limited",
            "wordfence",
        ],
    ),
    _WAFEntry(
        name="Radware AppWall",
        headers=[
            ("x-hw", None),
        ],
        cookies=["radware_"],
        body_markers=[
            "unauthorized activity has been detected",
            "security check has been performed",
        ],
    ),
    _WAFEntry(
        name="DDoS-Guard",
        headers=[
            ("server", "ddos-guard"),
        ],
        cookies=["__ddg1_", "__ddg2_", "__ddgid_"],
        body_markers=[
            "ddos-guard",
        ],
    ),
    _WAFEntry(
        name="Fastly",
        headers=[
            ("x-served-by", "cache-"),
            ("x-cache", "hit"),
            ("fastly-restarts", None),
        ],
        cookies=[],
        body_markers=[
            "fastly error: unknown domain",
        ],
    ),
    _WAFEntry(
        name="Nginx + naxsi",
        headers=[],
        cookies=[],
        body_markers=[
            "naxsi_sig",
            "<hr>naxsi",
        ],
    ),
]

_PROBE_PAYLOAD = "/?__waf_probe=1'+OR+'1'='1&<script>alert(1)</script>"

# ---------------------------------------------------------------------------
# HTTP helper
# ---------------------------------------------------------------------------

def _fetch(url: str, extra_path: str = "", timeout: float = 8.0) -> tuple[int, dict[str, str], list[str], str]:
    """Return (status, headers_lower, cookies, body_lower) for GET *url*+*extra_path*.

    cookies is a list of Set-Cookie header values (lower-case).
    Returns (-1, {}, [], "") on error.
    """
    try:
        parsed = urllib.parse.urlparse(url)
        is_https = parsed.scheme == "https"
        host = parsed.netloc or parsed.path
        path = (parsed.path or "/") + extra_path
        if parsed.query:
            path += "?" + parsed.query

        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        conn_cls = http.client.HTTPSConnection if is_https else http.client.HTTPConnection
        conn = conn_cls(host, timeout=timeout, **({"context": ctx} if is_https else {}))
        try:
            conn.request(
                "GET",
                path,
                headers={
                    "User-Agent": "Mozilla/5.0 (compatible; waf-detector/1.0)",
                    "Accept": "text/html,*/*",
                },
            )
            resp = conn.getresponse()
            status = resp.status
            headers_raw = resp.getheaders()
            body_raw = resp.read(8192)
        finally:
            conn.close()

        headers: dict[str, str] = {}
        cookies: list[str] = []
        for name, value in headers_raw:
            name_l = name.lower()
            value_l = value.lower()
            headers[name_l] = value_l
            if name_l == "set-cookie":
                cookies.append(value_l)

        body = body_raw.decode("utf-8", errors="replace").lower()
        return status, headers, cookies, body

    except Exception:
        return -1, {}, [], ""


# ---------------------------------------------------------------------------
# Scoring engine
# ---------------------------------------------------------------------------

class WAFSignal(NamedTuple):
    waf_name: str
    source: str   # "header" | "cookie" | "body"
    detail: str


def _score_response(
    headers: dict[str, str],
    cookies: list[str],
    body: str,
    context: str,
) -> list[WAFSignal]:
    """Return all WAF signals detected in this HTTP response."""
    signals: list[WAFSignal] = []
    cookie_blob = " ".join(cookies)

    for entry in _WAF_DB:
        # Header fingerprints
        for hdr_name, hdr_value in entry.headers:
            if hdr_name in headers:
                if hdr_value is None or hdr_value in headers[hdr_name]:
                    signals.append(WAFSignal(
                        waf_name=entry.name,
                        source="header",
                        detail=f"[{context}] Header '{hdr_name}'" +
                               (f" contains '{hdr_value}'" if hdr_value else " present"),
                    ))
                    break  # one signal per WAF per response category

        # Cookie fingerprints
        for ck_name in entry.cookies:
            if ck_name in cookie_blob:
                signals.append(WAFSignal(
                    waf_name=entry.name,
                    source="cookie",
                    detail=f"[{context}] Cookie matches '{ck_name}'",
                ))
                break

        # Body fingerprints
        for marker in entry.body_markers:
            if marker in body:
                signals.append(WAFSignal(
                    waf_name=entry.name,
                    source="body",
                    detail=f"[{context}] Body contains '{marker}'",
                ))
                break

    return signals


# ---------------------------------------------------------------------------
# Main detection logic
# ---------------------------------------------------------------------------

class WAFResult(NamedTuple):
    url: str
    verdict: str         # DETECTED | PROBABLE | NOT_DETECTED | ERROR
    waf_name: str        # "" if not detected
    signals: list[WAFSignal]
    detail: str


def _detect_waf(url: str, timeout: float = 8.0) -> WAFResult:
    """Run WAF detection against a single URL."""
    # Normalise URL
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    # Pass 1: normal request
    status1, headers1, cookies1, body1 = _fetch(url, timeout=timeout)
    if status1 == -1:
        # Try HTTP
        http_url = url.replace("https://", "http://", 1)
        status1, headers1, cookies1, body1 = _fetch(http_url, timeout=timeout)
        if status1 == -1:
            return WAFResult(url=url, verdict="ERROR", waf_name="", signals=[],
                             detail="Connection failed on both HTTPS and HTTP")

    signals: list[WAFSignal] = _score_response(headers1, cookies1, body1, "normal")

    # Pass 2: probe request with a simple injection payload
    status2, headers2, cookies2, body2 = _fetch(url, extra_path=_PROBE_PAYLOAD, timeout=timeout)
    if status2 != -1:
        signals += _score_response(headers2, cookies2, body2, "probe")
        # Block signal: if probe gets a different status than normal (403, 406, 429, 503)
        if status2 in (403, 406, 429, 503) and status1 not in (403, 406, 429, 503):
            signals.append(WAFSignal(
                waf_name="(unknown)",
                source="body",
                detail=f"[probe] Request blocked with HTTP {status2} (normal was {status1})",
            ))

    if not signals:
        return WAFResult(url=url, verdict="NOT_DETECTED", waf_name="", signals=[],
                         detail="No WAF fingerprints detected in normal or probe responses")

    # Count unique WAF names (excluding "(unknown)")
    name_counts: dict[str, int] = {}
    for sig in signals:
        if sig.waf_name != "(unknown)":
            name_counts[sig.waf_name] = name_counts.get(sig.waf_name, 0) + 1

    if name_counts:
        top_name = max(name_counts, key=lambda k: name_counts[k])
        top_count = name_counts[top_name]
        verdict = "DETECTED" if top_count >= 2 else "PROBABLE"
    else:
        top_name = "(unknown)"
        verdict = "PROBABLE"

    detail = f"{len(signals)} signal(s) matched"
    if top_name != "(unknown)":
        detail += f"; strongest match: {top_name} ({name_counts.get(top_name, 0)} signal(s))"

    return WAFResult(url=url, verdict=verdict, waf_name=top_name, signals=signals, detail=detail)


# ---------------------------------------------------------------------------
# Report formatter
# ---------------------------------------------------------------------------

def _run_waf_detect(urls: str, timeout: float = 8.0) -> str:
    """Core detection callable directly in tests."""
    targets = [u.strip() for u in urls.replace(",", "\n").splitlines() if u.strip()]
    if not targets:
        return "[waf_detector] Error: no URLs provided"

    lines: list[str] = [f"[waf_detector] Checking {len(targets)} target(s)\n"]

    detected = probable = not_detected = errors = 0

    for url in targets:
        result = _detect_waf(url, timeout)
        lines.append("─" * 60)
        lines.append(f"URL    : {url}")
        lines.append(f"Verdict: {result.verdict}")
        if result.waf_name and result.waf_name != "(unknown)":
            lines.append(f"WAF    : {result.waf_name}")
        lines.append(f"Detail : {result.detail}")

        if result.signals:
            lines.append("Signals:")
            for sig in result.signals:
                src_tag = {"header": "HDR", "cookie": "CKI", "body": "BDY"}.get(sig.source, sig.source.upper())
                lines.append(f"  [{src_tag}] {sig.waf_name:20s}  {sig.detail}")

        lines.append("")

        if result.verdict == "DETECTED":
            detected += 1
        elif result.verdict == "PROBABLE":
            probable += 1
        elif result.verdict == "NOT_DETECTED":
            not_detected += 1
        else:
            errors += 1

    lines.append("─" * 60)
    lines.append(f"Summary: {detected} DETECTED, {probable} PROBABLE, {not_detected} NOT_DETECTED, {errors} ERROR")

    if detected or probable:
        lines.append(
            "\nNote: A detected WAF does not mean bypass is impossible — "
            "it informs evasion strategy (encoding, IP rotation, header manipulation, slow-rate probing)."
        )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Function tool
# ---------------------------------------------------------------------------

@function_tool
def waf_detector(urls: str) -> str:
    """Detect Web Application Firewalls (WAF) in front of web targets.

    Passively fingerprints WAF products by analysing HTTP response headers,
    cookies, and body content.  Also sends a minimal probe request with a
    benign injection-like payload to trigger WAF block pages.

    Identifies: Cloudflare, AWS WAF/CloudFront, Akamai, Sucuri, Imperva/Incapsula,
    F5 BIG-IP, Barracuda, ModSecurity, Fortiweb, Wordfence, Radware AppWall,
    DDoS-Guard, Fastly, Nginx naxsi, and more via generic block-page detection.

    Args:
        urls: Newline- or comma-separated list of target URLs.
              Examples: "https://target.com" or "target.com, https://other.com"

    Returns:
        Formatted report with DETECTED / PROBABLE / NOT_DETECTED verdict per URL,
        the identified WAF product, and the signals that triggered the match.
    """
    return _run_waf_detect(urls)


TOOL_REGISTRY.register(
    "waf_detector",
    waf_detector,
    categories=["recon", "web"],
)
