"""Tests for WAF detector tool."""
import unittest
from unittest.mock import patch

from cai.tools.web.waf_detector import (
    WAFSignal,
    _detect_waf,
    _run_waf_detect,
    _score_response,
)


class TestScoreResponse(unittest.TestCase):
    def test_detects_cloudflare_via_header(self):
        headers = {"cf-ray": "abc123-LHR", "server": "cloudflare"}
        signals = _score_response(headers, [], "", "normal")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("Cloudflare", waf_names)

    def test_detects_cloudflare_via_cookie(self):
        cookies = ["cf_clearance=abc; path=/"]
        signals = _score_response({}, cookies, "", "normal")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("Cloudflare", waf_names)

    def test_detects_cloudflare_via_body(self):
        body = "attention required! | cloudflare"
        signals = _score_response({}, [], body, "normal")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("Cloudflare", waf_names)

    def test_detects_sucuri_via_header(self):
        headers = {"x-sucuri-id": "12345"}
        signals = _score_response(headers, [], "", "normal")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("Sucuri", waf_names)

    def test_detects_modsecurity_via_body(self):
        body = "this error was generated by mod_security"
        signals = _score_response({}, [], body, "probe")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("ModSecurity", waf_names)

    def test_no_false_positive_on_clean_response(self):
        headers = {"content-type": "text/html", "server": "nginx"}
        signals = _score_response(headers, [], "welcome to my site", "normal")
        self.assertEqual(signals, [])

    def test_detects_imperva_via_cookie(self):
        cookies = ["incap_ses_123=abcdef; path=/"]
        signals = _score_response({}, cookies, "", "normal")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("Imperva / Incapsula", waf_names)

    def test_detects_ddos_guard_via_cookie(self):
        cookies = ["__ddg1_=xyz; path=/"]
        signals = _score_response({}, cookies, "", "normal")
        waf_names = [s.waf_name for s in signals]
        self.assertIn("DDoS-Guard", waf_names)


class TestDetectWAF(unittest.TestCase):
    def _make_fetch(self, responses):
        """responses: list of (status, headers, cookies, body) in call order."""
        call_count = [0]
        def fake_fetch(url, extra_path="", timeout=8.0):
            idx = min(call_count[0], len(responses) - 1)
            call_count[0] += 1
            return responses[idx]
        return fake_fetch

    def test_detected_when_two_cf_signals(self):
        # Normal: cf-ray header + cloudflare server → 2 signals → DETECTED
        normal = (200, {"cf-ray": "abc", "server": "cloudflare"}, [], "")
        probe = (403, {}, ["cf_clearance=xyz"], "cloudflare ray id blocked")
        with patch("cai.tools.web.waf_detector._fetch", side_effect=self._make_fetch([normal, probe])):
            result = _detect_waf("https://example.com")
        self.assertEqual(result.verdict, "DETECTED")
        self.assertEqual(result.waf_name, "Cloudflare")

    def test_probable_when_one_signal(self):
        normal = (200, {"x-sucuri-id": "12345"}, [], "")
        probe = (200, {}, [], "")
        with patch("cai.tools.web.waf_detector._fetch", side_effect=self._make_fetch([normal, probe])):
            result = _detect_waf("https://example.com")
        self.assertEqual(result.verdict, "PROBABLE")

    def test_not_detected_when_clean(self):
        normal = (200, {"server": "nginx", "content-type": "text/html"}, [], "")
        probe = (200, {}, [], "")
        with patch("cai.tools.web.waf_detector._fetch", side_effect=self._make_fetch([normal, probe])):
            result = _detect_waf("https://example.com")
        self.assertEqual(result.verdict, "NOT_DETECTED")
        self.assertEqual(result.signals, [])

    def test_error_when_unreachable(self):
        with patch("cai.tools.web.waf_detector._fetch", return_value=(-1, {}, [], "")):
            result = _detect_waf("https://unreachable.example.com")
        self.assertEqual(result.verdict, "ERROR")

    def test_block_status_triggers_unknown_signal(self):
        # Normal 200, probe 403 → block signal added
        normal = (200, {}, [], "")
        probe = (403, {}, [], "")
        with patch("cai.tools.web.waf_detector._fetch", side_effect=self._make_fetch([normal, probe])):
            result = _detect_waf("https://example.com")
        # Should have at least 1 signal (the unknown block signal)
        self.assertGreater(len(result.signals), 0)
        block_signals = [s for s in result.signals if "(unknown)" in s.waf_name]
        self.assertGreater(len(block_signals), 0)

    def test_url_without_scheme_gets_https(self):
        normal = (200, {"cf-ray": "abc", "server": "cloudflare"}, [], "")
        probe = (200, {}, [], "")
        with patch("cai.tools.web.waf_detector._fetch", side_effect=self._make_fetch([normal, probe])) as mock_fetch:
            _detect_waf("example.com")
        # First call should use https://
        first_call_url = mock_fetch.call_args_list[0][0][0]
        self.assertTrue(first_call_url.startswith("https://"))


class TestRunWAFDetect(unittest.TestCase):
    def test_empty_input_returns_error(self):
        out = _run_waf_detect("")
        self.assertIn("Error", out)

    def test_whitespace_only_returns_error(self):
        out = _run_waf_detect("   \n  ")
        self.assertIn("Error", out)

    def test_summary_line_present(self):
        with patch("cai.tools.web.waf_detector._detect_waf") as mock_detect:
            from cai.tools.web.waf_detector import WAFResult
            mock_detect.return_value = WAFResult(
                url="https://example.com",
                verdict="NOT_DETECTED",
                waf_name="",
                signals=[],
                detail="No fingerprints",
            )
            out = _run_waf_detect("https://example.com")
        self.assertIn("Summary:", out)

    def test_comma_separated_targets(self):
        with patch("cai.tools.web.waf_detector._detect_waf") as mock_detect:
            from cai.tools.web.waf_detector import WAFResult
            mock_detect.return_value = WAFResult(
                url="", verdict="NOT_DETECTED", waf_name="", signals=[], detail="ok"
            )
            out = _run_waf_detect("https://a.com, https://b.com")
        self.assertEqual(mock_detect.call_count, 2)

    def test_detected_shows_note(self):
        with patch("cai.tools.web.waf_detector._detect_waf") as mock_detect:
            from cai.tools.web.waf_detector import WAFResult, WAFSignal
            mock_detect.return_value = WAFResult(
                url="https://target.com",
                verdict="DETECTED",
                waf_name="Cloudflare",
                signals=[WAFSignal("Cloudflare", "header", "cf-ray present"), WAFSignal("Cloudflare", "body", "body hit")],
                detail="2 signals",
            )
            out = _run_waf_detect("https://target.com")
        self.assertIn("Note:", out)
        self.assertIn("DETECTED", out)

    def test_tool_registered(self):
        from cai.tool_registry import TOOL_REGISTRY
        self.assertIn("waf_detector", TOOL_REGISTRY._tools)


if __name__ == "__main__":
    unittest.main()
